#!/usr/bin/env bash
# script configure nginx server to redrict to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
ssudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/intranet.alxswe.com\/projects\/266l;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start
