#!/usr/bin/env bash
# script configure nginx server to redrict to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' >  /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https://intranet.alxswe.com/projects/266l permanent;}" /etc/nginx/sites-available/default
sudo service nginx start
