#!/usr/bin/env bash
# script Configure Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' >  /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/intranet.alxswe.com\/projects\/266l permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-available/default
sudo service nginx start
