#!/usr/bin/env bash
# script Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y install haproxy
echo "\
frontend httb
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 419758-web-01 54.152.228.140:80
        server 419758-web-02 54.237.28.16:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null 2>&1
sudo service haproxy restart
